### ISSUE TITLE
[Package Manager Window] Error adding package: com.cesium.unity@1.5.0. aborted

### ISSUE THREAD

**Issue by 382993370** [CesiumGS/cesium-unity#353] opened 2023-08-09 03:28 UTC
Hello!  I tried to install cesium for unity1.5.0 many times, but I always failed. The warning is"[Package Manager Window] Error adding package: com.cesium.unity@1.5.0. aborted"
I followed the official website guide to enter the relevant url and scope, and confirmed that I can access github.com normally. What could be the cause of the problem?

**Comment by kring** [comment] 2023-08-09 21:41
Perhaps your network requires a proxy to access github, and Unity isn't using it?
The direct link to the v1.5.0 package is here:
https://github.com/CesiumGS/cesium-unity/releases/download/v1.5.0/com.cesium.unity-1.5.0.tgz
I've just confirmed that it is working correctly. So you can always download and install it manually if you need to.

I'm closing this because I don't think there's anything actionable for us here.

**Closed by kring** 2023-08-09 21:41 UTC
