### ISSUE TITLE
Limit Maps Tiles API Request AR App

### ISSUE THREAD

**Issue by NathalieTomas** [CesiumGS/cesium-unity#468] opened 2024-06-13 22:53 UTC
Hello,

We are currently developing an application using the Geospatial Creator API and the Cesium package to visualize objects in augmented reality. I added the Cesium license 5 hours ago and have used the augmented reality application three times at two different locations. However, I have already reached 20,000 requests on the Map Tiles API, making the 5 minutes of usage extremely expensive. Do you know how I can reduce these calls, considering that I do not need to visualize in the Unity editor and the usage is exclusively on a smartphone in AR?

Thank you for your help.

**Comment by kring** [comment] 2024-06-13 23:29
@NathalieTomas I'm a bit confused by your question. According to my understanding, Google Photorealistic 3D Tiles is billed by _root tile_ requests. In other words, fresh loads of the tileset. The number of requests for individual map tiles shouldn't matter.

**Comment by kring** [comment] 2024-06-13 23:30
In case it helps: if you don't want to show a Cesium3DTileset in the Editor, you can set its `updateInEditor` property to false.

**Comment by yumemi333** [comment] 2024-07-04 07:46
I think I am in the same situation.

When I refresh to load tiles, the number of API requests reaches over 300.
I would like to know if this is normal behavior and if there is any way to reduce the number of API requests.

**Comment by kring** [comment] 2024-07-24 15:47
@yumemi333 requesting 300+ individual tiles is normal, and shouldn't affect your billing. If you're seeing 300 requests for root.json, something is definitely wrong.

**Comment by j9liu** [comment] 2024-09-13 21:36
I'm closing this issue, since it seems more like a question rather than a confirmed bug or feature request. In the future, please post questions on our [community forum](https://community.cesium.com/). Thank you!

**Closed by j9liu** 2024-09-13 21:36 UTC
