### ISSUE TITLE
More Generic Camera Support

### ISSUE THREAD

**Issue by Reag** [CesiumGS/cesium-unity#394] opened 2024-01-22 08:37 UTC
I have a bit of an unusual use-case, where I have the player in a VR scene and want to provide them a secondary 'view' of a tileset on a render texture. In short, I wish to use a camera that's not Camera.main for driving Cesium's internal calculations. As it stands right now, it appears that the internal C# -> C++ Interop is hard coded to use Camera.main to simplify the hooks into the unity engine.

Would it be possible to allow for an override so we may pick which camera controls how the tilesets load? Having the ability to chose which camera projection matrix controls the screen-space error of the tilesets is critical for my use-case. Any resources that could help me accomplish this would be most welcome!

**Comment by kring** [comment] 2024-01-22 08:55
Duplicate of #327

**Closed by kring** 2024-01-22 08:55 UTC
