### ISSUE TITLE
DllNotFoundException: CesiumForUnityNative-Editor assembly:<unknown assembly> type:<unknown type> member:(null)

### ISSUE THREAD

**Issue by lzk9421** [CesiumGS/cesium-unity#496] opened 2024-08-31 02:46 UTC
Building Cesium for Unity

![PixPin_2024-08-31_10-45-10](https://github.com/user-attachments/assets/3e153b2e-6d26-4bfd-ac54-d25a2e0d3a24)

**Comment by kring** [comment] 2024-09-06 07:42
That error usually indicates you're either building for an unsupported platform, or you're building from source and haven't followed the developer setup instructions. I'm going to close this issue, because we only use issues for confirmed because and clear feature requests, but please post to the [community forum](https://community.cesium.com/c/cesium-for-unity/13) with more details about what you were trying to do when you got this error and we should be able to help you out.

**Closed by kring** 2024-09-06 07:42 UTC
